import type {
  BlogPost,
  DomainPrice,
  FooterSection,
  MenuItem,
  PricingPlan,
  Section,
  Testimonial,
} from "./types";

export const site = {
  name: "WEBCENTER HOSTING",
  tagline: "Reliable Web Hosting in Nigeria",
  primaryColor: "#080086",
  darkColor: "#05050b",
  accentColor: "#8fd313",
  supportEmail: "support@webcenter.ng",
  phone: "+234 706 308 9511",
  whatsapp: "+234 706 308 9511",
  address: "Lagos, Nigeria",
  currency: "₦",
  logoUrl: "/img/webcenter-logo.png",
  favicon: "/favicon.png",
  clientareaUrl: "https://webcenter.ng/host",
  social: {
    facebook: "#",
    twitter: "#",
    linkedin: "#",
    google: "#",
  },
  footer: {
    aboutText:
      "Webcenter Hosting provides reliable web hosting, domains, VPS, reseller hosting, SSL and support for businesses in Nigeria and beyond.",
    copyright: "© 2026 Webcenter Hosting. All rights reserved.",
  },
};

export function clientarea(path = ""): string {
  return site.clientareaUrl.replace(/\/$/, "") + path;
}

export const menus: MenuItem[] = [
  { label: "HOME", url: "/", icon: "fa-home" },
  {
    label: "HOSTING",
    url: "#",
    icon: "fa-server",
    children: [
      { label: "SHARED HOSTING", url: "/shared-hosting", icon: "fa-hdd-o" },
      { label: "RESELLER HOSTING", url: "/reseller-hosting", icon: "fa-users" },
      { label: "VPS HOSTING", url: "/vps-hosting", icon: "fa-cloud" },
      { label: "DEDICATED HOSTING", url: "/dedicated-hosting", icon: "fa-database" },
    ],
  },
  { label: "DOMAIN", url: "/domain", icon: "fa-globe" },
  {
    label: "PAGES",
    url: "#",
    icon: "fa-file-text-o",
    children: [
      { label: "ABOUT", url: "/about", icon: "fa-info-circle" },
      { label: "TESTIMONIAL", url: "/testimonial", icon: "fa-quote-left" },
    ],
  },
  { label: "BLOG", url: "/blog", icon: "fa-newspaper-o" },
  { label: "CONTACT", url: "/contact", icon: "fa-envelope-o" },
];

export const footerSections: FooterSection[] = [
  {
    title: "SERVICES",
    links: [
      { label: "Shared Hosting", url: "/shared-hosting" },
      { label: "Reseller Hosting", url: "/reseller-hosting" },
      { label: "VPS Hosting", url: "/vps-hosting" },
      { label: "Dedicated Hosting", url: "/dedicated-hosting" },
    ],
  },
  {
    title: "USEFUL LINKS",
    links: [
      { label: "Domain Search", url: "/domain" },
      { label: "Blog", url: "/blog" },
      { label: "Contact", url: "/contact" },
      { label: "Client Area", url: clientarea("/clientarea.php") },
    ],
  },
];

export const whyDarkItems: [string, string, string][] = [
  [
    "fa-sitemap",
    "Intuitive Interface",
    "Manage your domains, hosting, email accounts, SSL and website tools with a clean, beginner-friendly experience.",
  ],
  [
    "fa-trophy",
    "Built for Nigerian Businesses",
    "Fast hosting, local support and practical solutions designed for businesses that want to grow online.",
  ],
  [
    "fa-cubes",
    "All-in-one Business Solution",
    "Hosting, domain registration, website design, business email and digital infrastructure in one place.",
  ],
  [
    "fa-shield",
    "Reliability",
    "Stable servers, SSL security and dependable infrastructure for websites that must stay online.",
  ],
  [
    "fa-money",
    "Affordability",
    "Flexible plans and competitive pricing without compromising speed, security or support.",
  ],
  [
    "fa-headphones",
    "24/7 Customer Support",
    "Get help when you need it through WhatsApp, phone and support channels.",
  ],
];

export const pricingPlans: Record<string, PricingPlan[]> = {
  shared: [
    {
      id: "sh1",
      name: "Basic package",
      price: "2,000.00",
      popular: false,
      active: true,
      features: [
        "5 GB Disk Space",
        "30GB Monthly Bandwidth",
        "1 Hosted Addon Domain",
        "Free SSL Certificate",
        "10 Emails & Forwarders",
        "5 MySQL Databases",
        "5 Sub-domains",
      ],
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/store/shared-hosting-plans/basic-package",
    },
    {
      id: "sh2",
      name: "Standard Package",
      price: "3,000.00",
      popular: false,
      active: true,
      features: [
        "10 GB Disk Space",
        "Unlimited Monthly Bandwidth",
        "3 Hosted Addon Domain",
        "Free SSL Certificate",
        "10 Emails & Forwarders",
        "10 MySQL Databases",
        "20 Sub-domains",
      ],
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/store/shared-hosting-plans/standard-package",
    },
    {
      id: "sh3",
      name: "Stellar Business",
      price: "5,000.00",
      popular: true,
      active: true,
      features: [
        "40GB Disk Space",
        "UNLIMITED Monthly Bandwidth",
        "10 Hosted Addon Domain",
        "Free SSL Certificate",
        "UNLIMITED Emails & Forwarders",
        "UNLIMITED MySQL Databases",
        "UNLIMITED Sub-domains",
      ],
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/store/shared-hosting-plans/stellar-business",
    },
    {
      id: "sh4",
      name: "Unlimited Hosting",
      price: "20,000.00",
      popular: false,
      active: true,
      features: [
        "Unlimited Webspace",
        "Unlimited Bandwidth",
        "Unlimited Subdomains",
        "Unlimited Addon Domain",
        "Free dotNG Domain",
        "Free SSL Certificate",
        "Unlimited Emails",
      ],
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/store/shared-hosting-plans/unlimited-hosting",
    },
  ],
  vps: [
    {
      id: "vps1",
      name: "VPS 1",
      price: "25000",
      tagline: "Entry-level VPS power",
      popular: false,
      active: true,
      features: ["2 vCPU", "4 GB RAM", "80 GB SSD", "2 TB Bandwidth", "Full Root Access"],
      pid: 4,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=4",
    },
    {
      id: "vps2",
      name: "VPS 2",
      price: "45000",
      tagline: "For demanding applications",
      popular: true,
      active: true,
      features: ["4 vCPU", "8 GB RAM", "160 GB SSD", "4 TB Bandwidth", "Managed Support"],
      pid: 5,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=5",
    },
    {
      id: "vps3",
      name: "VPS 3",
      price: "75000",
      tagline: "Maximum VPS performance",
      popular: false,
      active: true,
      features: ["8 vCPU", "16 GB RAM", "320 GB SSD", "8 TB Bandwidth", "Priority Managed Support"],
      pid: 6,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=6",
    },
  ],
  dedicated: [
    {
      id: "ded1",
      name: "Dedicated Start",
      price: "120000",
      tagline: "Entry dedicated power",
      popular: false,
      active: true,
      features: ["Intel Xeon E3", "16 GB RAM", "500 GB SSD", "10 TB Bandwidth", "IPMI Access"],
      pid: 7,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=7",
    },
    {
      id: "ded2",
      name: "Dedicated Pro",
      price: "180000",
      tagline: "High-performance workloads",
      popular: true,
      active: true,
      features: ["Dual Intel Xeon", "32 GB RAM", "1 TB SSD", "20 TB Bandwidth", "Full Management"],
      pid: 8,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=8",
    },
    {
      id: "ded3",
      name: "Enterprise Server",
      price: "250000",
      tagline: "Enterprise-grade power",
      popular: false,
      active: true,
      features: ["Dual Intel Xeon Gold", "64 GB RAM", "2 TB NVMe SSD", "Unlimited Bandwidth", "24/7 Managed Support"],
      pid: 9,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=9",
    },
  ],
  reseller: [
    {
      id: "res1",
      name: "Bronze Reseller",
      price: "15000",
      tagline: "Start your hosting business",
      popular: false,
      active: true,
      features: ["50 GB Disk Space", "500 GB Bandwidth", "20 cPanel Accounts", "Free WHMCS License", "WHM Control Panel"],
      pid: 10,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=10",
    },
    {
      id: "res2",
      name: "Silver Reseller",
      price: "30000",
      tagline: "Grow your client base",
      popular: true,
      active: true,
      features: ["100 GB Disk Space", "1 TB Bandwidth", "50 cPanel Accounts", "Free WHMCS License", "Private Nameservers"],
      pid: 11,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=11",
    },
    {
      id: "res3",
      name: "Gold Reseller",
      price: "50000",
      tagline: "For established resellers",
      popular: false,
      active: true,
      features: ["200 GB Disk Space", "2 TB Bandwidth", "Unlimited cPanel", "Free WHMCS License", "Priority Support"],
      pid: 12,
      currency: "₦",
      billing_cycle: "monthly",
      order_url: "https://webcenter.ng/host/cart.php?a=add&pid=12",
    },
  ],
};

export const domainPricing: DomainPrice[] = [
  { ext: ".com", register: "25000", renew: "25000", transfer: "23000" },
  { ext: ".net", register: "28000", renew: "28000", transfer: "26000" },
  { ext: ".org", register: "25000", renew: "25000", transfer: "23000" },
  { ext: ".com.ng", register: "4500", renew: "4500", transfer: "4000" },
  { ext: ".ng", register: "13500", renew: "13500", transfer: "12000" },
  { ext: ".info", register: "18000", renew: "20000", transfer: "17000" },
];

export const blogPosts: BlogPost[] = [
  {
    id: "bp1",
    title: "10 Reasons to Choose SSD Hosting",
    slug: "ssd-hosting-benefits",
    status: "published",
    author: "Admin",
    date: "2025-05-10",
    category: "Tutorials",
    excerpt:
      "SSD hosting offers dramatically faster load times compared to traditional HDD hosting. Learn the top 10 benefits for your website.",
    image: "/img/blog-img/post-01.png",
    tags: ["SSD", "Performance", "Hosting"],
  },
  {
    id: "bp2",
    title: "VPS vs Shared Hosting: Which is Right for You?",
    slug: "vps-vs-shared-hosting",
    status: "published",
    author: "Admin",
    date: "2025-05-05",
    category: "Guides",
    excerpt:
      "Choosing the right hosting type is crucial for your website's success. We break down the key differences between VPS and shared hosting.",
    image: "/img/blog-img/post-02.png",
    tags: ["VPS", "Shared Hosting", "Guide"],
  },
  {
    id: "bp3",
    title: "How to Secure Your Website with Free SSL",
    slug: "free-ssl-guide",
    status: "draft",
    author: "Admin",
    date: "2025-05-14",
    category: "Security",
    excerpt:
      "SSL certificates are essential for website security and SEO. This guide shows you how to enable your free SSL certificate.",
    image: "",
    tags: ["SSL", "Security", "HTTPS"],
  },
];

export function publishedPosts(limit = 0): BlogPost[] {
  const posts = blogPosts.filter((p) => p.status === "published");
  return limit ? posts.slice(0, limit) : posts;
}

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Johnson",
    role: "CEO, TechStart Inc.",
    quote:
      "Webcenter Host has been absolutely outstanding. Our site load times dropped by 60% after switching to their SSD plans. The support team is always ready to help.",
    image: "/img/testimonial-img/client-01.jpg",
    active: true,
  },
  {
    id: "t2",
    name: "Michael Chen",
    role: "Lead Developer, WebCraft",
    quote:
      "I've tried many hosting providers over the years, and Webcenter Hosting is by far the most reliable. Zero downtime in 18 months. Incredible service.",
    image: "/img/testimonial-img/client-02.jpg",
    active: true,
  },
  {
    id: "t3",
    name: "Emma Williams",
    role: "Founder, DigitalBloom",
    quote:
      "The VPS plans gave us exactly the scalability we needed as our business grew. Migration was seamless and the control panel is intuitive.",
    image: "/img/testimonial-img/client-03.jpg",
    active: true,
  },
];

const HERO_IMAGE = "/img/web-hosting-hero.webp";

export const pageSections: Record<string, Section[]> = {
  home: [
    {
      id: "home_hero",
      page_id: "home",
      section_type: "hero",
      title: "Fast, Secure & Affordable Hosting for Your Website",
      subtitle:
        "Buy domains, launch websites, and manage hosting with reliable speed, free SSL, and expert support from Webcenter Hosting.",
      image: HERO_IMAGE,
      button_text: "Get Started Now",
      button_link: clientarea("/cart.php"),
      sort_order: 10,
    },
    {
      id: "home_domain",
      page_id: "home",
      section_type: "domain_search",
      title: "Register Your Domain",
      subtitle: "Search, register, transfer, and manage your domains easily — all in one place.",
      sort_order: 20,
    },
    {
      id: "home_shared_pricing",
      page_id: "home",
      section_type: "pricing",
      title: "Shared Hosting Plans",
      subtitle: "Affordable hosting plans with SSD storage, free SSL, email accounts and easy WHMCS ordering.",
      options: { plan_type: "shared" },
      sort_order: 30,
    },
    {
      id: "home_vps_pricing",
      page_id: "home",
      section_type: "pricing",
      title: "VPS Hosting Plans",
      subtitle: "Flexible VPS resources for growing websites and applications.",
      options: { plan_type: "vps" },
      sort_order: 40,
    },
    {
      id: "home_dedicated_pricing",
      page_id: "home",
      section_type: "pricing",
      title: "Dedicated Hosting Plans",
      subtitle: "Premium dedicated server plans for mission-critical workloads.",
      options: { plan_type: "dedicated" },
      sort_order: 50,
    },
    {
      id: "home_why",
      page_id: "home",
      section_type: "why_dark",
      title: "Why Webcenter Hosting?",
      subtitle: "Reliable hosting built for entrepreneurs, businesses, agencies and growing brands.",
      sort_order: 60,
    },
    {
      id: "home_blog",
      page_id: "home",
      section_type: "blog",
      title: "Latest Articles",
      subtitle: "Helpful hosting, website and domain resources.",
      options: { limit: 2 },
      sort_order: 70,
    },
    {
      id: "home_cta",
      page_id: "home",
      section_type: "contact_strip",
      title: "Need help choosing the right hosting plan?",
      subtitle:
        "Our experienced support team can guide you on hosting, domains, business email, SSL certificates, VPS, dedicated servers and website solutions.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  shared: [
    {
      id: "shared_hero",
      page_id: "shared",
      section_type: "hero",
      title: "Shared Hosting Built for Small Businesses",
      subtitle: "Affordable hosting plans with SSD storage, free SSL, email accounts and easy WHMCS ordering.",
      image: HERO_IMAGE,
      button_text: "View Plans",
      button_link: "#pricing",
      sort_order: 10,
    },
    {
      id: "shared_pricing",
      page_id: "shared",
      section_type: "pricing",
      title: "Shared Hosting Plans",
      subtitle: "Choose the right shared hosting package for your website.",
      options: { plan_type: "shared" },
      sort_order: 20,
    },
    {
      id: "shared_features",
      page_id: "shared",
      section_type: "features",
      title: "Why Choose Our Shared Hosting?",
      subtitle: "Everything needed to launch a fast and secure website.",
      options: {
        items: [
          { icon: "fa-rocket", title: "Fast SSD Storage", text: "Optimized resources for quick website loading." },
          { icon: "fa-lock", title: "Free SSL", text: "Protect your website and improve customer trust." },
          { icon: "fa-envelope", title: "Business Email", text: "Create professional email accounts for your domain." },
        ],
      },
      sort_order: 30,
    },
    {
      id: "shared_cta",
      page_id: "shared",
      section_type: "contact_strip",
      title: "Need help choosing a shared hosting plan?",
      subtitle: "Talk to our team and we will recommend the best package for your website.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  reseller: [
    {
      id: "reseller_hero",
      page_id: "reseller",
      section_type: "hero",
      title: "Start Your Own Hosting Business",
      subtitle: "Reseller hosting plans built for agencies, developers, and entrepreneurs.",
      image: HERO_IMAGE,
      button_text: "View Plans",
      button_link: "#pricing",
      sort_order: 10,
    },
    {
      id: "reseller_pricing",
      page_id: "reseller",
      section_type: "pricing",
      title: "Reseller Hosting Plans",
      subtitle: "Choose Reseller Hosting for your growing hosting business.",
      options: { plan_type: "reseller" },
      sort_order: 20,
    },
    {
      id: "reseller_features",
      page_id: "reseller",
      section_type: "features",
      title: "Reseller Hosting Features",
      subtitle: "Tools and resources for growing your hosting business.",
      options: {
        items: [
          { icon: "fa-users", title: "Host Multiple Clients", text: "Manage many customer websites from one reseller account." },
          { icon: "fa-cogs", title: "Easy Management", text: "Control plans, domains, and accounts with a simple workflow." },
          { icon: "fa-money", title: "Recurring Income", text: "Build monthly hosting revenue from your existing clients." },
        ],
      },
      sort_order: 30,
    },
    {
      id: "reseller_cta",
      page_id: "reseller",
      section_type: "contact_strip",
      title: "Ready to start your hosting brand?",
      subtitle: "Our team can help you choose the right reseller package.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  vps: [
    {
      id: "vps_hero",
      page_id: "vps",
      section_type: "hero",
      title: "Powerful VPS Hosting",
      subtitle: "Scalable virtual servers with more control, better speed, and dedicated resources.",
      image: HERO_IMAGE,
      button_text: "View Plans",
      button_link: "#pricing",
      sort_order: 10,
    },
    {
      id: "vps_pricing",
      page_id: "vps",
      section_type: "pricing",
      title: "VPS Hosting Plans",
      subtitle: "Choose flexible VPS resources for growing websites and apps.",
      options: { plan_type: "vps" },
      sort_order: 20,
    },
    {
      id: "vps_features",
      page_id: "vps",
      section_type: "features",
      title: "Why Choose VPS Hosting?",
      subtitle: "More control and performance for your customers’ websites.",
      options: {
        items: [
          { icon: "fa-server", title: "Dedicated Resources", text: "Get isolated resources for stable performance." },
          { icon: "fa-terminal", title: "Root Access", text: "Enjoy more control over your server environment." },
          { icon: "fa-arrows-alt", title: "Scalable Power", text: "Upgrade resources as your website grows." },
        ],
      },
      sort_order: 30,
    },
    {
      id: "vps_cta",
      page_id: "vps",
      section_type: "contact_strip",
      title: "Need help selecting VPS resources?",
      subtitle: "We can guide you on RAM, CPU, storage and bandwidth requirements.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  dedicated: [
    {
      id: "dedicated_hero",
      page_id: "dedicated",
      section_type: "hero",
      title: "Dedicated Servers for Serious Workloads",
      subtitle: "High-performance dedicated hosting for businesses that need power, privacy, and reliability.",
      image: HERO_IMAGE,
      button_text: "View Plans",
      button_link: "#pricing",
      sort_order: 10,
    },
    {
      id: "dedicated_pricing",
      page_id: "dedicated",
      section_type: "pricing",
      title: "Dedicated Hosting Plans",
      subtitle: "Premium dedicated server plans for mission-critical workloads.",
      options: { plan_type: "dedicated" },
      sort_order: 20,
    },
    {
      id: "dedicated_features",
      page_id: "dedicated",
      section_type: "features",
      title: "Why Choose Dedicated Servers?",
      subtitle: "Maximum performance and control for high-demand businesses.",
      options: {
        items: [
          { icon: "fa-microchip", title: "High Performance", text: "Dedicated compute power for heavy websites and applications." },
          { icon: "fa-lock", title: "Private Environment", text: "Isolated server resources for better privacy and control." },
          { icon: "fa-database", title: "Large Storage", text: "Flexible storage options for business workloads." },
        ],
      },
      sort_order: 30,
    },
    {
      id: "dedicated_cta",
      page_id: "dedicated",
      section_type: "contact_strip",
      title: "Need a custom dedicated server setup?",
      subtitle: "Speak with us about CPU, RAM, storage, backup and security requirements.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  domain: [
    {
      id: "domain_hero",
      page_id: "domain",
      section_type: "hero",
      title: "Find and Register Your Perfect Domain",
      subtitle: "Search, register, transfer, and manage your domain from one place.",
      image: HERO_IMAGE,
      button_text: "Search Now",
      button_link: "#domain-search",
      sort_order: 10,
    },
    {
      id: "domain_search",
      page_id: "domain",
      section_type: "domain_search",
      title: "Register Your Domain",
      subtitle: "Search, register, transfer, and manage your domains easily — all in one place.",
      sort_order: 20,
    },
    {
      id: "domain_features",
      page_id: "domain",
      section_type: "features",
      title: "Domain Services Made Easy",
      subtitle: "Simple domain registration and management for businesses.",
      options: {
        items: [
          { icon: "fa-search", title: "Easy Domain Search", text: "Quickly check availability for your preferred name." },
          { icon: "fa-random", title: "Domain Transfer", text: "Move your domain to us and manage everything together." },
          { icon: "fa-lock", title: "Domain Privacy", text: "Protect your contact details where supported." },
          { icon: "fa-globe", title: "Popular Extensions", text: "Register .com, .net, .org, .ng and more." },
        ],
      },
      sort_order: 30,
    },
    {
      id: "domain_cta",
      page_id: "domain",
      section_type: "contact_strip",
      title: "Need help choosing a domain name?",
      subtitle: "We can help you choose a professional domain for your brand.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  about: [
    {
      id: "about_hero",
      page_id: "about",
      section_type: "hero",
      title: "About Webcenter Host",
      subtitle:
        "Reliable hosting, domain registration, SSL certificates and website solutions built for businesses that want to grow online.",
      image: HERO_IMAGE,
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 10,
    },
    {
      id: "about_why",
      page_id: "about",
      section_type: "why_dark",
      title: "Who We Are",
      subtitle: "We focus on speed, security, support, and practical digital infrastructure for Nigerian businesses.",
      sort_order: 20,
    },
    {
      id: "about_testimonials",
      page_id: "about",
      section_type: "testimonials",
      title: "What Clients Say",
      subtitle: "Feedback from businesses using our hosting services.",
      sort_order: 30,
    },
    {
      id: "about_cta",
      page_id: "about",
      section_type: "contact_strip",
      title: "Let’s help your business grow online.",
      subtitle: "Talk to us about hosting, domains, email and website solutions.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  contact: [
    {
      id: "contact_hero",
      page_id: "contact",
      section_type: "hero",
      title: "Contact Webcenter Host",
      subtitle: "We are here to help with hosting, domains, servers, websites and support.",
      image: HERO_IMAGE,
      button_text: "Get Support",
      button_link: "https://webcenter.ng/host/submitticket.php",
      sort_order: 10,
    },
    {
      id: "contact_info",
      page_id: "contact",
      section_type: "custom_html",
      title: "Get in Touch",
      subtitle: "Reach our team through phone, WhatsApp or email.",
      content:
        '<div class="row"><div class="col-md-4"><h3>Phone</h3><p>+234 704 423 4511</p></div><div class="col-md-4"><h3>WhatsApp</h3><p>+234 810 462 0701</p></div><div class="col-md-4"><h3>Client Area</h3><p><a href="https://webcenter.ng/host">Open client area</a></p></div></div>',
      sort_order: 20,
    },
    {
      id: "contact_cta",
      page_id: "contact",
      section_type: "contact_strip",
      title: "Need urgent hosting support?",
      subtitle: "Open a support ticket or chat with our team on WhatsApp.",
      button_text: "Open Client Area",
      button_link: "https://webcenter.ng/host",
      sort_order: 90,
    },
  ],
  blog: [
    {
      id: "blog_hero",
      page_id: "blog",
      section_type: "hero",
      title: "Webcenter Hosting Blog",
      subtitle: "Tips, guides and updates to help you manage your website better.",
      image: HERO_IMAGE,
      button_text: "Read Articles",
      button_link: "#blog",
      sort_order: 10,
    },
    {
      id: "blog_list",
      page_id: "blog",
      section_type: "blog",
      title: "Latest Articles",
      subtitle: "Helpful hosting, website and domain resources.",
      options: { limit: 6 },
      sort_order: 20,
    },
    {
      id: "blog_cta",
      page_id: "blog",
      section_type: "contact_strip",
      title: "Need help with your website or hosting?",
      subtitle: "Our team can help you choose the right solution.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
  testimonial: [
    {
      id: "testimonial_hero",
      page_id: "testimonial",
      section_type: "hero",
      title: "What Our Clients Say",
      subtitle: "Real feedback from businesses that trust Webcenter Hosting.",
      image: HERO_IMAGE,
      button_text: "Get Started Now",
      button_link: clientarea("/cart.php"),
      sort_order: 10,
    },
    {
      id: "testimonial_list",
      page_id: "testimonial",
      section_type: "testimonials",
      title: "Happy Client Reviews",
      subtitle: "What our customers say about Webcenter Host.",
      sort_order: 20,
    },
    {
      id: "testimonial_cta",
      page_id: "testimonial",
      section_type: "contact_strip",
      title: "Ready to join thousands of happy customers?",
      subtitle: "Get started with reliable hosting today.",
      button_text: "Contact Us",
      button_link: "/contact",
      sort_order: 90,
    },
  ],
};
